name: Call a composit action
description: 'Build a given package'
inputs:
  pkg-name:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Build ${{ inputs.pkg-name }}
      run: ./scripts/hello.py ${{ inputs.pkg-name }}
      shell: python
