name: Example Workflow

on: [push]

env:
  matrix_file: matrix.txt

jobs:
  build:
    name: Build
    runs-on: macos-13
    steps:
      - name: Install strong type
        run: |
          brew tap a4z/cpp-taps
          brew install strong_type

      - name: List brews
        run: |
          brew list
