name: Explor action things
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
    
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run command based on operating system
      if: ${{ matrix.os == 'windows-latest' }}
      run: powershell .\windows.ps1
      env:
        OS: Windows
    - name: Run command based on operating system
      if: ${{ matrix.os == 'macOS-latest' }}
      run: bash ./macOS.sh
      env:
        OS: macOS
    - name: Run command based on operating system
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: bash ./ubuntu.sh
      env:
        OS: Ubuntu
