name: Explor action things
on: push

name: create-packages
on:
  push:
    branches:
        - feature/*
        - main
        - p/ha1672/SWC-1500-AutoGen-Bazel-Files # todo, remove when not needed anymore

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2019]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install buildozer
      run: go install github.com/bazelbuild/buildtools/buildozer@latest
    - name: Run buildozer
      run: buildozer --version
