name: Explore callable workflows
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/buildpkg.yml
        with:
          pkg-name: first
      - uses: ./.github/actions/buildpkg.yml
        with:
          pkg-name: second


