name: Explore callable workflows
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install something via apt
        if:  ${{ startsWith(matrix.os,'ubuntu') }}
        run: sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: First
        uses: ./.github/actions/build-pkg
        with:
          pkg-name: first
      - name: Second
        uses: ./.github/actions/build-pkg
        if:  ${{ startsWith(matrix.os,'ubuntu') }}
        with:
          pkg-name: second


