name: Example Workflow

on: [push]

env:
  matrix_file: matrix.txt

jobs:
  build:
    name: Build
    runs-on: ${{ fromJson(file(env.matrix_file)).os }}
    env:
      package: ${{ fromJson(file(env.matrix_file)).package }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment information
        run: |
          echo "Operating system: ${{ fromJson(file(env.matrix_file)).os }}"
          echo "Package: ${{ fromJson(file(env.matrix_file)).package }}"

      - name: Build package
        run: |
          # Add build command here, replacing '<package>' with '${{ env.package }}'
          echo "Building package: ${{ env.package }}"
