name: Explore callable workflows
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]

    runs-on: ${{ matrix.os }}
    steps:
      build-pkg1:
        uses: ./.github/workflows/buildpkg.yml
        with:
          pkg-name: first

      build-pkg2:
        uses: ./.github/workflows/buildpkg.yml
        with:
          pkg-name: second


