name: Explor action things
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run command based on operating system
      if: ${{ matrix.os == 'windows-latest' }}
      run: Write-Host "Running on Windows"
      env:
        OS: Windows
    - name: Run command based on operating system
      if: ${{ matrix.os == 'macOS-latest' }}
      run: echo "Running on macOS"
      env:
        OS: macOS
    - name: Run command based on operating system
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: echo "Running on Linux"
      env:
        OS: Ubuntu
    - name: Another step
      run: |
        echo "Running on $env:OS"
