name: Explor action things
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Check NDK
      run: ls /usr/local/lib/android/sdk/ndk/
    - name: Check NDK content
      run: ls /usr/local/lib/android/sdk/ndk/25.1.8937393

      

