name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "a4z"          
      - name: explore 
        run: |
          ls ${ANDROID_SDK_ROOT}/ndk
          echo "----------"
          ls ${ANDROID_SDK_ROOT}/ndk -C1 | sort -r | head -1
