name: Dynamic steps example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate steps file
      run: |
        chmod a+x ./generate.sh
        ./generate.sh

    - name: Use generated steps
      run: cat steps.yml | sed 's/^/    /' >> $GITHUB_WORKFLOW
