name: Example Workflow

on: [push]

env:
  matrix:
    - os: ubuntu-18.04
      package: a b c
    - os: ubuntu-20.04
      package: a c e
    - os: macOS-12
      package: c d f

jobs:
  build:
    name: Build
    runs-on: ${{ env.matrix.os }}
    env:
      package: ${{ env.matrix.package }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print environment information
        run: |
          echo "Operating system: ${{ env.matrix.os }}"
          echo "Package: ${{ env.matrix.package }}"

      - name: Build package
        run: |
          # Add build command here, replacing '<package>' with '${{ env.package }}'
          echo "Building package: ${{ env.package }}"
