name: Example Workflow

on: [push]

env:
  matrix_file: matrix.txt

jobs:
  v1:
    name: Install v1
    runs-on: macos-13
    steps:
      - name: Install strong type
        run: |
          brew tap a4z/cpp-taps
          brew install strong_type

      - name: List brews
        run: |
          brew info strong_type

  v2:
    name: Install v2
    runs-on: macos-13
    steps:
      - name: Install strong type
        run: |
          brew install brew install a4z/cpp-taps/strong_type

      - name: List brews
        run: |
          brew info strong_type
