name: Dynamic steps example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate steps file
      run: |
        chmod a+x ./generate.sh
        ./generate.sh
        cat ./steps.yml

    - name: Use generated steps
      uses: ./steps.yml

