name: Explor action things
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
    
    runs-on: ${{ matrix.os }}
    steps:
    - name: Run command based on operating system
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          Write-Host "Running on Windows"
        elif [ "${{ matrix.os }}" == "macOS-latest" ]; then
          echo "Running on macOS"
        elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          echo "Running on Ubuntu Linux"
        fi
