name: Explor action things
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-20.04, windows-2019]

    runs-on: ${{ matrix.os }}
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install buildozer
      run: go install github.com/bazelbuild/buildtools/buildozer@latest
    - name: Run buildozer
      run: buildozer --version
