name: Explor action things
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-18.04
    steps:
#       - uses: actions/checkout@v1
#       - uses: ./action-a
#         with:
#           MY_NAME: "a4z"          
      - name: explore 
        run: |
          ls ${ANDROID_SDK_ROOT}/
          echo "----------"
          ls ${ANDROID_SDK_ROOT}/ndk
          echo "----------"
          ls ${ANDROID_SDK_ROOT}/ndk -C1 | sort -r | head -1
          echo "----------"
          ls ${ANDROID_SDK_ROOT}/ndk/$(ls ${ANDROID_SDK_ROOT}/ndk -C1 | sort -r | head -1)

      - name: exploreMore
        run: |
          env | grep ANDROID
